---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  product_version: '14.12.9' # <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once
  retry_on_exit_code:
    - 0
    - 1 # Exit, success: You still must reboot, this just notes that the automatic restart flag was removed
    - 2 # Exit, success, need to reboot
    - 3 # Exit, success, with a non-critical failure: Typically seen when returning the DNS Delegation warning.
    - 4 # Exit, success, with a non-critical failure, need to reboot: Typically seen when returning the DNS Delegation warning.
    - 35 # 35 is the exit code signaling that the node is rebooting
    - 1190 #1190 is the exit code signaling that a reboot is scheduled
  wait_for_retry: 200 # May need to increase depending on computing resources.
  max_retries: 1

transport:
  name: winrm
  elevated: true  # Required to get Windows Update to run
  winrm_transport: plaintext  # When set to plaintext the winrm will run in one converge

platforms:
#  - name: windows-2008-r2
#     driver_config:
#       box_url:
  - name: windows-2008-r2-core
#    driver_config:
#      box_url:
#  - name: windows-2012
#    driver_config:
#      box_url:
  - name: windows-2012-r2
#    driver_config:
#      box_url:
#  - name: windows-2012-r2-core
#    driver_config:
#      box_url:
  - name: windows-2016
#    driver_config:
#      box_url:
#  - name: windows-2016-core
#    driver_config:
#      box_url:

suites:
  - name: default
    run_list:
      - recipe[windows_ad::default]
    attributes:

  - name: forest
    run_list:
      - recipe[test_windows_ad::setup_forest]
      - recipe[test_windows_ad::ou]
    attributes:
